keys:
  - &admin_ayu age1u3asm98exz9ff3qdlm46p5v005usrp530s63hjq85wk8wplf7ygq28vmhy 
  - &server_nextcloud age1xch7tl6puppr28fmuzuwjskz9z0u0lwe4plwy92u2xuzvq48rstqcde6ea
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *admin_ayu
  - path_regex: secrets/nextcloud\.yaml
    key_groups:
    - age:
      - *server_nextcloud
