keys:
  - &admin_ayu age1u3asm98exz9ff3qdlm46p5v005usrp530s63hjq85wk8wplf7ygq28vmhy
#  - &server_nextcloud <-insert age here->
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_ayu
#      - *server_nextcloud
